### ISSUE TITLE
Folders are not scaled properly

### ISSUE THREAD

**Issue by mattsc02** [LawnchairLauncher/Lawnchair#106]
Folders are a little bit bigger than app icons

**Comment by deletescape** [comment]
Should be improved, is it better now?

**Comment by mattsc02** [comment]
![screenshot_20170706-073000](https://user-images.githubusercontent.com/29816872/27898284-348e4d0a-621d-11e7-825a-eaedc5855486.png)
No, not really. Separate icon size and folder icon size sliders could be added maybe?

**Comment by intelligentcasanova** [comment]
It is Pixel Launcher's default behaviour to show folders a bit bigger than application icons. Furthermore, folder icons scale with the icon size setting. 
@deletescape can this issue be closed?

**Comment by fonix232** [comment]
@deletescape one thing is for sure, our love for you is not because of your consistency 😂

**Comment by nyancrimew** [comment]
@fonix232 probably also not for being 100% focused on everything at all times :wink:
