### ISSUE TITLE
libswresample.so: text relocations on x86 CPU

### ISSUE THREAD

**Issue by TheArda** [LawnchairLauncher/Lawnchair#119]

**Comment by deletescape** [comment]
Can you provide some additional information, and maybe a logcat for this and #118? 

I don't think I have this problem on my emulators which are x86 too afaik

**Comment by TheArda** [comment]
![screenshot_20170704-165251](https://user-images.githubusercontent.com/10501401/27832971-65ad829c-60d9-11e7-813e-805aadb8b55b.png)

**Comment by TheArda** [comment]
[logcat.txt](https://github.com/Deletescape-Media/Lawnchair/files/1122270/logcat.txt)

**Comment by TheArda** [comment]
What do you mean about  additional information ? , is there any other logs ?

**Comment by fonix232** [comment]
Additional info such as device type, OS version, et cetera.

Looking at your logcat, I can see that you had an old version of Lawnchair installed, and there are some warnings due to that (some permissions are not granted, and might be related to this).

**Comment by charliecantsurf** [comment]
I'm having the same issue as seen in the screenshot. I'm running the launcher on Asus Zenfone 2 ZE551ML booting LineageOS, Android 7.1.2. Please advise.

**Comment by TheArda** [comment]
Device : Zenfone 5
Os version : 7.1.2
Rom : Lineage os 14.1

**Comment by kobiandy** [comment]
Same phone same issue

**Comment by yusoofsh** [comment]
lets bring this up. i got this too.
i think problem exist when using api25 and x86 arch

**Comment by JackGitrocks-19** [comment]
Still having this issue, please fix it devs...(Lineage OS 14.1 builds-Z00A-->>x86)
