### ISSUE TITLE
I SAD LIKE A SAD BOY IS ME IS A SAD ME

### ISSUE THREAD

**Issue by ghost** [LawnchairLauncher/Lawnchair#1199]
till is no make a Pixel new launcher I am a sad me is so sad and no I no forgive I wait so many long year many many and I mad and sad angry human being like it is only a launcher why is so long no code learn how? I smart too much is me like a bag bag. Big forgile had me lunch yesterday I ated a hotdog no mustard and till still no launcher I want to die today.

**Comment by ZerNico** [comment]
No u
You are as smart as a bag bag, that's awesome!

**Comment by shubhchan** [comment]
@sadgals New launcher will come soon ,half members working on v1 to fix bugs(almost done) and other half are preparing v2 ,and soon u will get it

**Comment by abhijeetbohra** [comment]
@ZerNico Haha me too thanks

**Comment by ZerNico** [comment]
@abhijeetbohra But I am as smart as a rucksack
