### ISSUE TITLE
Grey navbar buttons on Galaxy S8 devices.

### ISSUE THREAD

**Issue by lunsarn** [LawnchairLauncher/Lawnchair#120]
Stupid TouchWiz software thinks launcher is an app with white navbar and makes navbar buttons grey looks bad on most wallpapers. Nova has this fixed with white navbar buttons. (Stock TouchWiz launcher uses white buttons also.)

**Comment by lunsarn** [comment]
http://imgur.com/a/hO40l

**Comment by lunsarn** [comment]
@fonix232 Enhancement? I would label it a bug 😁 Thanks anyway! Regards lunsarn.

**Comment by deletescape** [comment]
It's not really a bug, as it doesn't actually break any functionality, it's just not that beautiful :joy:

**Comment by fonix232** [comment]
It's not technically a bug, since it works as intended. It's not a feature, because not all devices benefit from this. So what remains is enhancement, which is technically "polishing existing features".

**Comment by akapu1** [comment]
Please fix this issue for S8. Thank you..

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ghost** [comment]
Pretty sure every other launcher except this one doesn't have this bug not just Nova

**Comment by lunsarn** [comment]
@v0idst4r True. Samsungs execution of the on-screen navbar buttons is pretty bad overall.

**Comment by ghost** [comment]
@lunsarn After checking, I guess most other 3rd party launchers have this bug as well. (Action launcher and even google now launcher).

Maybe the developer of nova can explain how he fixed it because previous versions of nova had this bug as well.

**Comment by tfadgreef** [comment]
Hi,
Is there any solution for this issue?

**Comment by ghost** [comment]
It'd be closed if we knew.

**Comment by akapu1** [comment]
please fix this issue.. it's really annoying..!

**Comment by ghost** [comment]
Personally I stopped noticing it.

**Comment by drew5494** [comment]
I mean, the navbuttons, theyre just so grey
I can't believe theyre just so dark, it's like out there
I mean gross  
I like white navbuttons

**Comment by ghost** [comment]
Using the dark theme helps make them look better
