### ISSUE TITLE
Pixel Square and Rounded Square icons

### ISSUE THREAD

**Issue by Dondrejohnson5** [LawnchairLauncher/Lawnchair#139]
Have option to make Pixel icons other than default circles, like squares, round squares, etc, as shown here
![icons-shape](https://user-images.githubusercontent.com/29732079/27912450-fd30062e-622a-11e7-9d4c-32715f30f64f.jpg)

**Comment by jacksonhvisuals** [comment]
Yeah, this would be awesome

**Comment by ACHOKAMAN** [comment]
Awesome....please this feature can be added

**Comment by AxiK101** [comment]
Nice!!💪

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by mattcooperkay** [comment]
This is definitely my most wanted feature - square icons are awful!

**Comment by 109021017** [comment]
My most wanted feature too!
