### ISSUE TITLE
Request "Hide Apps" automatically from drawer when place on homescreen(s) option

### ISSUE THREAD

**Issue by haydnlj** [LawnchairLauncher/Lawnchair#145]
Manually do this now - personally think that an app should be in one place, not two!

**Comment by fonix232** [comment]
This might be implemented as an option in the future, but not for now.

**Comment by haydnlj** [comment]
Awesome response time!

**Comment by fonix232** [comment]
No need to close the issue, I just indicated that this will be considered at a later point. Since the "issue" is not solved, it should stay open :)
