### ISSUE TITLE
App not updating thought XDA-LABS

### ISSUE THREAD

**Issue by ghost** [LawnchairLauncher/Lawnchair#146]
So I checked today the xda labs app and the app is still using 198-Travis version.

**Comment by Dondrejohnson5** [comment]
https://github.com/Deletescape-Media/Lawnchair/releases

**Comment by edisso10018** [comment]
Why is this an issue with Lawnchair? Why do you post it here?

**Comment by deletescape** [comment]
I will be uploading the new releases on XDA lab as soon as I have time. I am really busy with other stuff. Main release channels are github and telegram
