### ISSUE TITLE
Gesture Support

### ISSUE THREAD

**Issue by deletescape** [LawnchairLauncher/Lawnchair#20]
Open apps / do certain actions with gestures like double tap, swipe up, etc

**Comment by tomato18** [comment]
Like the swipe down to search feature. Can there be an option to change it to expand the notification drawer instead?

**Comment by TokedUp** [comment]
Swipe up from home screen should open app drawer from anywhere. Swipe down should open notifications from anywhere. Please make these options

**Comment by deletescape** [comment]
@TokedUp Swipe up from anywhere already opens App drawer, swipe down to open notifications has just been added, and after all, this is still my project and I would not even have to implement it this way if I wouldn't want to.

**Comment by AxiK101** [comment]
Double tap to sleep and you are ready to go

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by LinuxLlama** [comment]
Is this still going to be considered? People on G+ really want this stuff including me.
