### ISSUE TITLE
Pixel Bar keeps disappearing

### ISSUE THREAD

**Issue by SeanForester27** [LawnchairLauncher/Lawnchair#27]
I've noticed that I don't get a 1 next to an app if there's a notification..do i need to do something to make this work?

**Comment by SeanForester27** [comment]
Also on your latest build and I know it's a test build but the pixel bar keeps disappearing...only way it comes back is if i swipe up into the app drawer and then go back home...

**Comment by deletescape** [comment]
To get the notification dots to work you have to go to settings and enable notification access for Lawnchair.
And yeah, pixel bar sometimes disappears sometimes right now, I don't yet know why but I should have it fixed by next week

**Comment by SeanForester27** [comment]
Yeah...so Lawnchair does have access to notifications..in the settings it says "allow" unless there is another area for me to do it at..then it's broke.

**Comment by SeanForester27** [comment]
I'm also on a S8..

**Comment by SeanForester27** [comment]
Even in the app permissions section under SMS..Lawnchair isn't even there...

**Comment by SeanForester27** [comment]
Disregard..i finally found it. Samsung hides stuff.

**Comment by deletescape** [comment]
Damn, Blame Samsung

**Comment by deletescape** [comment]
Reopening this, will use it to track progress for the pixel bar disappearing problem

**Comment by SeanForester27** [comment]
Ok, then also I just found another issue..icons keep getting very pixelized...wish i could send a picture of it..

**Comment by SeanForester27** [comment]
Restart of phone is the only way i can fix it..

**Comment by fosser2** [comment]
Amazing launcher, this issue does persist on my S8 as well though. Confirmed that it does indeed come back after opening app drawer and then clicking home.

**Comment by versavius** [comment]
Perhaps when installing the launcher it should prompt for access to notifications? This would help to stop people asking this question in future, or maybe an option in settings stating notifications are not active unless you [click here] to activate it, then by clicking it can popup to request the relevant permission?
