### ISSUE TITLE
Import

### ISSUE THREAD

**Issue by klzjr** [LawnchairLauncher/Lawnchair#33]
Option to import from other launchers

**Comment by deletescape** [comment]
An Option to import / export from/to lawnchair (and maybe other launcher3 based launchers) will be added in the future

**Comment by beatbrot** [comment]
@deletescape I'd try working on this, if you still want it to be implemented :) Just answer as soon as you can :)

**Comment by nyancrimew** [comment]
@beatbrot this would be highly appreciated! Send a PR whenever you have it

**Comment by beatbrot** [comment]
Yup, already made *some* progress, but will take some time as I dont have too much freetime right now :) At least, I can already query the APIs of other launchers :) so it is now just inserting into lawnchair, what is left :)

**Comment by nyancrimew** [comment]
Perfect, thanks for your efforts!

**Comment by beatbrot** [comment]
Alright, made some progress, but I have some questions on how to handle stuff: 
Let's say we have the following situation: We want to import from ActionLauncher(with a 10x10 Grid) into LawnChair(with a 4x4 Grid). 

- What do we do with items outside of our grid?
- How do we handle stuff like sub-grid-positioning in other launchers?

**Comment by nyancrimew** [comment]
There is the class `ch.deletescape.lawnchair.model.GridSizeMigrationTask` it should be able to help you migrate from different grid sizes.

For sub grid positioning we should probably just round for now and make sure nothing overlaps (as this doesn't work in lawnchair yet and would probably cause crashes). We can still change that if we add the feature in the future.

**Comment by scho0ck** [comment]
Just wondering if there is any progress on this feature as it is the only reason why I haven't fully switched 

Thanks

**Comment by crutchcorn** [comment]
Has there been any work on this issue? I am beta testing v2 and can't seem to find this feature present

**Comment by r4lex** [comment]
I'd also like to know.

**Comment by StonedMonkey97** [comment]
??????????

**Comment by 0x11DFE** [comment]
It is 2022 is there any progress guy's ?

**Comment by jo-chemla** [comment]
This import feature would be great for helping users migrate from existing launchers - be it default stock launcher, manufacturer one (Pixel, Samsung one UI, Xiaomi miui etc) or other launcher apps (Niagara, Nova etc).

At least for the homepage which is often the more complex piece to set-up when switching launcher.
