### ISSUE TITLE
Double tap to lock device

### ISSUE THREAD

**Issue by NitemareReal** [LawnchairLauncher/Lawnchair#40]
Double tap on desktop to lock device

**Comment by amirzaidi** [comment]
https://github.com/VertexOS/android_packages_apps_Launcher3/commit/a30709ea01d3df9aa2c60ab692f16031a8036d08

This is the way PA does it in their Launcher3, maybe it'll be of help.

**Comment by deletescape** [comment]
Thanks @amirzaidi for the help, will add it in, but it will only work if the app is a system app

**Comment by alexandrumarcel** [comment]
@deletescape You don't really need to use the app as a system app.. You could use the Device Administrator option like Nova Launcher does:

http://imgur.com/a/QiLHf

**Comment by deletescape** [comment]
Thanks for the heads up @alexandrumarcel I will definetly provide an implementation of some kind

**Comment by Trak-X** [comment]
I already implemented something like this in the launcher as a personal test. I still have some issues with it and will polish it some more. If you want, when I finish, I can push to git and you can test it. Problem is: I am using root, and was thinking of using device admin for non rooted devices.

**Comment by deletescape** [comment]
@Trak-X if you are able to get a functional implementation for rooted / non-rooted users I'd appreciate a PR!

**Comment by Trak-X** [comment]
Ok. Will add both and let you know when done. Should not be too long.

**Comment by kobiandy** [comment]
+1

**Comment by kobiandy** [comment]
Was this implemented in the 818 build? If yes mine not working. RR Z00A

**Comment by fonix232** [comment]
@kobiandy Is this issue ticket closed? No. Thus it wasn't implemented.

**Comment by xmiseggs** [comment]
@Trak-X Hi, how's the development going? Can we have this option soon ?, thank you.

**Comment by ghost** [comment]
gib clay

**Comment by Trak-X** [comment]
Not yet, sorry. Until i don't get a good solution for rooted and unrooted devices, i will not submit a pull request.

Sorry for the delay. So many things on my head right now.

**Comment by mg712702** [comment]
guys i am also want double tap to lock gesture on lawnchair............

**Comment by enricocid** [comment]
I added dt to lock on my launcher
You can use my code if you want
https://github.com/enricocid/LaunchEnr

Look at simplegestures, workspace, admin XML...

**Comment by Secuential** [comment]
I recommend also adding the non root, fingerprint-reader friendly, lock method: when you dt, change the screen timeout to 5secs and put a black screen meanwhile. Because device admin kills fingerprint unlocking. Nova, Evie and many launchers can use this method too :)

**Comment by Seohol** [comment]
We are still waiting this feature:( I'am Google Pixel owner and I've to stuck on Nova Launcher only because of this feature (cry)

> screen timeout to 5secs and put a black screen meanwhile

This way works well, please add to Lawnchair

**Comment by yzhelezko** [comment]
screen timeout to 5secs and put a black screen meanwhile +1

**Comment by capstan1** [comment]
Also came here in search for this feature I got very used to, using Evie.

The black screen thing always worked perfect for me on my unrooted Moto Z (with fingerprint)

Would make your awesome launcher perfect!

PS: just want to say, I'm really impressed how development improved! I used it shortly after it first appeared in my newsfeed and just came back. Boy, what a change!

**Comment by rini94** [comment]
So, is this still in plan?

**Comment by divadsn** [comment]
@rini94 Yes, but right now we are busy finalizing v1 :)

**Comment by rinerate** [comment]
+1 I dont use Lawnchair only because Lawnchair doesnt have this feauture. Please add!

**Comment by axis0093** [comment]
waiting for this feature

**Comment by bohrabhijeet** [comment]
@axis0093 This feature is already present in v1 and in v2 as well.

**Comment by axis0093** [comment]
@abhijeetbohra Found it, thank you
