### ISSUE TITLE
Add Text wrapping

### ISSUE THREAD

**Issue by jool3z** [LawnchairLauncher/lawnchair#4517]
### Describe the feature

It would be great if text wrapping under the icons on the main screen and the app overview would be implemented. This should be optional and selectable in the preferences.

### Why would it be useful to add?

Especially app names that can't be shortened sensible will ne cut.
![Screenshot_20240626-225031](https://github.com/LawnchairLauncher/lawnchair/assets/88937963/5deea9f1-22c8-47e5-8518-53bf8d8f8726)

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

In this example "Assistant" should be moved in the second line and only cut if the name is extremely long.

**Comment by CoelacanthusHex** [comment]
Enable option "Use Multiple Line" in setting.

**Comment by slhale** [comment]
I think "Did the feature exist in Lawnchair v2? (Play Store version)" should be "yes" for this one 


> Enable option "Use Multiple Line" in setting.

@CoelacanthusHex in which part of the settings is this? I don't see it

**Comment by CoelacanthusHex** [comment]
> I think "Did the feature exist in Lawnchair v2? (Play Store version)" should be "yes" for this one
> 
> > Enable option "Use Multiple Line" in setting.
> 
> @CoelacanthusHex in which part of the settings is this? I don't see it

It was introduced in https://github.com/LawnchairLauncher/lawnchair/commit/7c34d0c16021305b2a48324100f58eab4527e8cb

**Comment by slhale** [comment]
> It was introduced in [7c34d0c](https://github.com/LawnchairLauncher/lawnchair/commit/7c34d0c16021305b2a48324100f58eab4527e8cb)

Ah, maybe I should switch from the beta build to nightly

**Comment by MrSluffy** [comment]
Done : 7c34d0c16021305b2a48324100f58eab4527e8cb
