### ISSUE TITLE
Persistent Search Bar

### ISSUE THREAD

**Issue by Dondrejohnson5** [LawnchairLauncher/Lawnchair#58]
Allow option for search bar to be persistent (to be seen on any home screen, like the Pixel C Launcher)

**Comment by LifeWulf** [comment]
I'm not entirely certain how GitHub works, but I guess I'll just say "I second this"?

**Comment by OvermindDL1** [comment]
> I'm not entirely certain how GitHub works, but I guess I'll just say "I second this"?

The usual Github way to support an issue is to click the plus-HappyFace at the top-right of the top comment and select the thumbs up.  :-)

Whenever someone posts a message, like I am doing here, it is EMailing it to every person listening on this issue and/or entire repo, which can become thousands to hundreds of thousands to millions on the largest projects.  :-)

**Comment by LifeWulf** [comment]
I see. Sorry everyone, that little "plus happy face" doesn't show on the mobile site!

**Comment by OvermindDL1** [comment]
> I see. Sorry everyone, that little "plus happy face" doesn't show on the mobile site!

All good, just the process of learning Github.  :-)

There is a mobile site for github?!  I always got the full Desktop site on my phone, wonder why I do not get the mobile site when I have mobile enabled, hmm...  You've made me curious about that now...  ^.^

**Comment by LifeWulf** [comment]
Are you using Google Chrome?
![screenshot_20170629-110029](https://user-images.githubusercontent.com/9089275/27694501-4595ac0a-5cba-11e7-8df4-cf9973cd61e4.png)

**Comment by OvermindDL1** [comment]
> Are you using Google Chrome?

Yep, standard android Google Chrome, Desktop mode checkbox option is disabled.  Hmm...

There seem to be no media-queries in the CSS that do anything like that, so it looks like they are serving actual different content based on what they are detecting, and it must be detecting wrong (server-side browser detection is always a stupid choice).  Interesting...

**Comment by versavius** [comment]
As long as the search bar can be disabled (hidden) that works i dont use the search and prefer my homescreen to be clean, but an on/off feature works for everyone :)
