### ISSUE TITLE
BUG: Rendering error.

### ISSUE THREAD

**Issue by StreetLightsOfficial** [LawnchairLauncher/Lawnchair#78]
![xpkzfky](https://user-images.githubusercontent.com/9665212/27614645-e08526e4-5b9a-11e7-9ff0-dfd1f96e0f28.png)
Very thin line of pixels on the app menu. Also experiencing the stutter issue reported by other users.
OnePlus 3t on OxygenOS 4.1.6

**Comment by intelligentcasanova** [comment]
Is this still an issue? @deletescape

**Comment by nyancrimew** [comment]
@intelligentcasanova yes it is, but only when a custom DPI is used
