### ISSUE TITLE
Tablet Support

### ISSUE THREAD

**Issue by Dondrejohnson5** [LawnchairLauncher/Lawnchair#89]
Please support tablets. This layout looks ridiculous
![screenshot_20170628-164844](https://user-images.githubusercontent.com/29732079/27659668-599cc60e-5c22-11e7-94ce-3c2c7d35b2e4.png)
![screenshot_20170628-164855](https://user-images.githubusercontent.com/29732079/27659673-5f271b24-5c22-11e7-8048-87caf34a0f96.png)
![screenshot_20170628-164915](https://user-images.githubusercontent.com/29732079/27659680-64e1f3e0-5c22-11e7-9d33-c59e62027424.png)

**Comment by deletescape** [comment]
Ummm, yeah it does :joy: I knew it would look weird, but.... THAT WEIRD 🤣

**Comment by Stanzilla** [comment]
The current alpha builds work fine on tablets, not sure about v1, is tablet installation going to be enabled via the Play Store?
