### ISSUE TITLE
Google Pill widget does not re-scale when column number changes

### ISSUE THREAD

**Issue by kirbyfan64** [LawnchairLauncher/Lawnchair#99]
...and now the time and date got shifted in a really weird way:

[![Screenshot_20170629-122313.png](https://s5.postimg.org/444adso7b/Screenshot_20170629-122313.png)](https://postimg.org/image/hl18wnyir/)

BTW is there a way to *not* make the left side of the G button gray?

**Comment by kirbyfan64** [comment]
FWIW restarting the app fixed the issue.

**Comment by fonix232** [comment]
I'll see if I can make the widget reload when the column number changes, so it automatically resizes.

As for the gray bar, it can be removed, might make it an option later on.

**Comment by kirbyfan64** [comment]
> As for the gray bar, it can be removed, might make it an option later on.

Please do! :D

**Comment by AxiK101** [comment]
Nice wall and profile pic

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
